
server:
  port: 8083

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/books-management-db?createDatabaseIfNotExist=true
#    username: root
#    password: pool
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
#  application:
#    name: AUTHOR-SERVICE

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
spring:
  datasource:
    url: jdbc:mysql://${DB_SERVER}:${DB_PORT:3306}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: AUTHOR-SERVICE

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka